JuliaDebug/JuliaInterpreter.jl

src/JuliaInterpreter.jl
src/interpret.jl
src/localmethtable.jl
test/interpret.jl

 Fix `getproperty` calls and handle Core.Typeof(Vararg)

---

src/JuliaInterpreter.jl

fix docs for determine_method_for_expr

---

src/interpret.jl
test/interpret.jl

This gives "correct" line numbers for method code (at least as correct as Julia allows it).

slightly better line numbers

---

src/interpret.jl
test/toplevel.jl
test/toplevel_script.jl

fix struct definitions with getproperty in them

---

src/JuliaInterpreter.jl
test/toplevel.jl

fix interpret macro to handle subtyping

---

test/utils.jl

See the new instructions in #13.

Make it easier to create useful bug reports from Julia tests

---

src/interpret.jl
test/interpret.jl

Calling this function `location` is promising a bit too much.

rename location to linenumber

---

src/JuliaInterpreter.jl
test/toplevel.jl

Every package technically has Main as its parent (e.g., during precompilation), but unless you've said `using MyPkg` the name may not be visible in Main. Thus when a new module expression is encountered, we need to check to see if it's a loaded package.

Find modules in loaded packages

---

src/interpret.jl
test/breakpoints.jl

This seems more in line with how I think a user would except break on error to work. Discussion welcome :)

only break if we are throwing an uncaught exception

---

src/breakpoints.jl
test/breakpoints.jl

These were discovered while adding a new REPL mode to Rebugger, one that provides an IDE-like interface. It's pretty addictive. https://github.com/timholy/Rebugger.jl/pull/61

Small fixes to breakpoint operation

---

docs/make.jl
docs/src/dev_reference.md

So we see if doctests start failing.

add the last documented function to index and enable strict

---

src/JuliaInterpreter.jl

To make me sleep easier at night

use last_reference instead for locals

---

Manifest.toml
Project.toml
test/utils.jl

For the purposes of testing, run `SHA.update!` in compiled mode.

Work around #101

---

test/breakpoints.jl

This is a commit I found lying around, thought I should add it before I get started on the linked-list implementation. I should have added this in #96, but better late than never.

Test breakpoint location for kwarg functions

---

test/utils.jl

Fix typo in test/utils.jl

---

src/commands.jl
test/debug.jl

ensure we leave wrapper if we step to the end of it

---

src/construct.jl
test/breakpoints.jl
test/debug.jl

 Fix "sg" for parametric generated functions 

---

src/interpret.jl
test/interpret.jl

fix accessing undef sparam

---

src/JuliaInterpreter.jl
src/commands.jl
src/construct.jl
test/debug.jl

 Ensure slots get assigned in `finish_stack!`

---

src/JuliaInterpreter.jl

Fixes https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/170

fix what project is used when building builtins

---

src/commands.jl
test/debug.jl

This should probably be documented?

use compiled mode when there is no chance we will encounter a breakpoint

---

src/commands.jl
test/debug.jl

Reverts JuliaDebug/JuliaInterpreter.jl#180
We forgot `@bp`...

Revert "use compiled mode when there is no chance we will encounter a breakpoint"

---

src/commands.jl
src/generate_builtins.jl
src/utils.jl
test/debug.jl

Step through invokelatest

---

src/commands.jl
test/debug.jl

ensure si doesn't step over anything

---

src/utils.jl
test/interpret.jl

Fixes https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/200

fix undef sparam in locals

---

src/construct.jl
test/toplevel.jl

Ref https://github.com/JuliaLang/julia/issues/31470#issuecomment-476368692

Check nargs when extracting doc expressions

---

src/commands.jl
test/debug.jl

fix assertion when breakpoint triggers during wrapper step through

---

src/optimize.jl

Having a bit of a hard time coming up with a test.

fix bug when passing static parameters

---

src/optimize.jl
test/interpret.jl

I missed the `QuoteNode`s we insert.

also match ccalls against (lib, function)

---

test/interpret.jl

Closes https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/154

add a test for deepcopy on QuoteNode

---

test/interpret.jl

Closes https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/194

add a test for calling Meta.parse error

---

src/optimize.jl

Get rid of the unnecessary function that are left after we move the foregincall to the wrapper function.
Using
```jl
julia> const ss = "foo"
"foo"
julia> p = pointer_from_objref(ss)
Ptr{Nothing} @0x0000000007f1b2d0
```
Before
```jl
julia> @btime @interpret unsafe_pointer_to_objref(p)
6.100 μs (54 allocations: 2.72 KiB)
"foo"
```
After
```jl
julia> @btime @interpret unsafe_pointer_to_objref(p)
4.543 μs (40 allocations: 2.20 KiB)
"foo"
```

Delete leftover cconvert and unsafe_convert after moving foreigncall to wrapper function

---

src/optimize.jl

Didn't know about this one. Fixes the segfault on master win32

fix using the correct calling convention on win32

---

src/optimize.jl
test/interpret.jl

Missed this in https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/120.
Fixes #267

fix for undefined GlobalRefs

---

Project.toml
REQUIRE

Might as well get https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/277 and https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/275 into a release.

release v0.5.1

---

src/interpret.jl
test/toplevel.jl

Fixes https://github.com/timholy/Revise.jl/issues/304

Support self-referential struct definitions

---

bin/generate_builtins.jl
src/JuliaInterpreter.jl
src/builtins.jl
src/construct.jl

This is just a copy/paste of the fix that @vtjnash very helpfully supplied in https://github.com/JuliaLang/julia/pull/31895#issue-275146433

Circumvent removal of `append_any` from nightly (fixes #282)

---

Project.toml

- Refactoring of breakpoints to allow breakpoints in lines to be set without using Revise (#259)
- Support self-referential struct definitions (#283)

Update version to 0.6.0

---

src/interpret.jl

Not quite sure what to do about a test; my effort in #289 failed to catch this and without Revise I'm not sure how to trigger it.

Re-fix #288

---

src/interpret.jl
src/optimize.jl

fix for change in Julia foreigncall

---

docs/Manifest.toml
docs/make.jl
docs/src/dev_reference.md
src/construct.jl
src/utils.jl
test/eval_code.jl
test/runtests.jl

This is a useful feature but needs access to internals of JuliaInterpreter so best to just define it here.
cc @pfitzseb.

add util functionality for evaluating code in a frame

---

Project.toml
src/builtins.jl
test/interpret.jl

fix typo in #kw##invoke builtin

---

src/construct.jl
test/toplevel.jl

This is a little weird, ~~and I have not been able to come up with a good test~~, but it's needed for Revise issue 302.

Check that the id appears in Base.loaded_modules

---

src/utils.jl
test/interpret.jl

fix codelocation in the presence of meta nodes

---

src/interpret.jl

Fixes breakage from https://github.com/JuliaLang/julia/pull/34176

Evaluating %new expressions: prepare args and ccall jl_new_structv

---

src/breakpoints.jl
src/types.jl
src/utils.jl
test/breakpoints.jl

Seems to work fine afaict, but still needs tests.
Fixes https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/368.

global breakpoints

---

Project.toml

Seem OK? Or is there more we want to get into this?

Version 0.7.10

---

src/utils.jl
test/interpret.jl

Fixes #374.
Right now I'm just creating a fake name in the case of a Module, I don't think it is shown anywhere, so hopefully ok.

Fix StackFrame for top level frames

---

src/optimize.jl
src/utils.jl

xref https://github.com/JuliaLang/julia/issues/35922

Reduce invalidations due to untyped fields of CodeInfo

---

src/optimize.jl
src/types.jl

Improves printing if you want to display `frame.framecode.src`.

Utility for undoing more of the optimization

---

src/utils.jl
test/eval_code.jl

Fixes https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/399

also maybe_quote ssavalues and locals

---

src/utils.jl
test/interpret.jl

~~Not sure how to best test this though.~~ Now with tests.

isdefined check in locals()

---

src/utils.jl
test/eval_code.jl
test/interpret.jl

only add Boxes with defined contents to list of locals

---

src/utils.jl
test/core.jl
test/runtests.jl

Fix typo in `is_quoted_type`

---

bin/generate_builtins.jl
src/breakpoints.jl
src/builtins.jl
src/commands.jl
src/construct.jl
src/interpret.jl
src/optimize.jl
src/types.jl
src/utils.jl
test/breakpoints.jl

Same body of work as https://github.com/JuliaLang/julia/pull/36255

Fix invalidations from extending `==(::SomeType, ::Any)`

---

src/commands.jl
src/interpret.jl
src/optimize.jl
src/utils.jl
test/debug.jl
test/limits.jl
test/utils.jl

These new IR types were added in https://github.com/JuliaLang/julia/pull/36318. Also fixes a couple of other issues noticed along the way.

Support ReturnNode and GotoIfNot

---

src/interpret.jl
src/packagedef.jl
src/utils.jl

These were triggered by loading FillArrays

Use `mapany` to avoid some broadcasting invalidations

---

test/breakpoints.jl
test/interpret.jl
test/limits.jl
test/toplevel.jl

This was pulled out of #406 as an independently-worthy improvement.

Run more tests in isolation

---

docs/src/ast.md
docs/src/internals.md

Hopefully this will get the tests passing (xref https://travis-ci.org/github/JuliaDebug/JuliaInterpreter.jl/jobs/727028903)

Fix doc links

---

src/construct.jl
test/toplevel.jl

Don't split scope-modifying blocks

---

src/breakpoints.jl
src/utils.jl
test/debug.jl

The most important change is for https://github.com/JuliaLang/julia/pull/37573.

Various fixes on nightly

---

src/optimize.jl
test/interpret.jl

Fixes https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/433.
I feel like this is probably not the correct fix, but it works, so... ¯\\\_(ツ)\_/¯

fix at-ccall?

---

src/construct.jl
test/toplevel.jl

Revise has to be able to analyze code in modules that are not in
the namespace. It turns out that differences between how discovery
works in interactive mode (which implicitly widens the Manifest to
include all the stdlibs) and test-mode (which does not) have caused
trouble for the discovery of toplevel modules for some time:
it turns out we've been constructing "shadow" modules of the same names
as these stdlibs. Some of the exclusions in Revise's `sigtest.jl` test
file reflect this.
This PR makes ExprSplitter try harder to find modules from
`Base.__toplevel__`. When we can't resolve the name in the manifest,
we also check `Base.loaded_modules` and see if we can find something with
that name.
This fixes a bug that just arose (but whose roots are old) for
Revise on nightly …

Try harder to find __toplevel__ stdlibs in ExprSplitter

---

src/builtins.jl
src/optimize.jl
src/utils.jl
test/debug.jl
test/interpret.jl
test/toplevel.jl

commits taken from #437 and #449, so this should probably not be squashed. Just fixes the tests and addresses some warnings on top of those PRs.
closes #437
closes #449

fix failures on nightly 2

---

test/interpret.jl

Fixes https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/470.

httpbingo.julialang.org for HTTP test

---

.gitignore
src/interpret.jl
src/packagedef.jl
src/types.jl
test/code_coverage/code_coverage.jl
test/code_coverage/coverage_example.jl
test/code_coverage/coverage_example.jl.cov
test/runtests.jl

Still need to write some tests and perhaps run some benchmarks, but
seems to work, at least for simple cases.

report coverage when interpreting

---

README.md

This wasn't updated when we switched from travis to GH actions.

update badge for CI

---

src/commands.jl
test/debug.jl

Fixes https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/435.

Fix kwarg wrapper detection for Unions

---

bin/generate_builtins.jl
src/builtins.jl
test/interpret.jl

this will prevent them from crashing, but will not allow stepping into them.

very slight support for `OpaqueClosure`s

---

src/interpret.jl

See https://github.com/JuliaLang/julia/pull/51590.

Adjust to upcoming julia lowering change

---

.github/workflows/CI.yml
.github/workflows/Documenter.yml

30 min should be plenty for now. CI sometimes just hangs so let's not use up 6h of unnecessary CI time

set CI timeout

---

src/types.jl

Slightly improving type stability.

remove `AbstractFrameInstance`

---

src/construct.jl
test/toplevel.jl

This is a very minimal fix, reasoning that `global` annotations are common at toplevel but `local` ones are not. When I fixed #427, there was no good reason to avoid splitting on `global`, I don't know why I did that.
We might someday want to rewrite `ExprSplitter` more extensively, but that would likely be a breaking change.
Fixes https://github.com/timholy/Revise.jl/issues/718
Also adds nested docstring test

Fix revise#718

---

src/interpret.jl

Fixes https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/610
Refs https://github.com/JuliaLang/julia/pull/52245

adapt to implicit leave change in Julia

---

.github/workflows/CI.yml
bin/generate_builtins.jl
src/breakpoints.jl
src/builtins.jl
src/commands.jl
src/construct.jl
src/interpret.jl
src/optimize.jl
src/types.jl
src/utils.jl
test/breakpoints.jl
test/code_coverage/code_coverage.jl
test/debug.jl
test/eval_code.jl
test/interpret.jl
test/limits.jl
test/toplevel_script.jl

not yet passing, but fixes many of the issues

some updates required for Julia v1.11

---

src/utils.jl
test/debug.jl
test/utils.jl

Just what I happned to see driving by.

Some more 1.12 compat

---

src/breakpoints.jl
test/breakpoints.jl

fixes JuliaDebug/Debugger.jl#327

fix breakpoints for keyword functions

---

test/interpret.jl

ref https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/593#discussion_r1753734294
Co-authored-by: Shuhei Kadowaki <aviatesk@gmail.com>

follow-up #593

---

src/commands.jl
src/utils.jl
test/debug.jl

Closes #620
(So glad I get to do this again! :laughing: )

Fix kwprep stepping in Julia 1.12 and 1.11

---

src/optimize.jl
src/packagedef.jl
src/types.jl
test/debug.jl
test/utils.jl

This doesn't get all tests passing, but most uses of breakpoints now
work.

Improve breakpoints on Julia 1.12

---

src/construct.jl

Adapts to https://github.com/JuliaLang/julia/pull/57230

Update generated functions for Julia 1.12

---

src/interpret.jl

The fallback code for the three-argument form of `@lookup` is never actually reached, so there is no need to maintain this version. The module context can always be taken from the `frame`. For these reasons, the three-argument version of `@lookup` is deprecated and will be removed in v0.10.

deprecate 3-arg `@lookup`
