JuliaDebug/JuliaInterpreter.jl

- src/interpret.jl
This should restore `nightly` to working order.
> Handle :splatnew expressions on nightly

- src/JuliaInterpreter.jl
- src/interpret.jl
- src/precompile.jl
This doesn't help a lot:
```julia
julia> using JuliaInterpreter
julia> @time @interpret sum(rand(5))
5.571196 seconds (2.70 M allocations: 125.351 MiB, 0.40% gc time)
2.2449034191308073
```
but it does shave ~1s off on my machine. Most of the time is spent in LLVM, so until we can cache native code I don't think there's much we can do.
> Add some precompile statements for faster startup

- test/juliatests.jl
- test/utils.jl
This adds an enormous test suite for JuliaInterpreter: all of Julia's own tests. It is presumably impractical to run these on Travis, but local devs can do so. The idea here is to use this to see how robust (or not) JuliaInterpreter really is. (If anyone has ideas about how to get them to run on PRs without bogging things down too much, I'm all ears.)
The tests do not pass yet, but this allows people to work towards that goal. Meanwhile I'll get started on an issue that flags failures and some of the reasons why. Help (even just triaging files that pass and those that do not) would be very welcome!
> Add test harness for running all of Julia's tests

- src/interpret.jl
- test/interpret.jl
> Allow ccalls that hardcode 2 Symbols

- src/interpret.jl
- test/interpret.jl
rethrow is only viable inside a `catch`, so we need to intercept it and convert it to an ordinary `throw`.
In my hands, this was perhaps the single biggest limitation of JuliaInterpreter. I frequently got
```julia
julia> @test ret == ErrorException("inner")
Test Failed at REPL[10]:1
Expression: ret == ErrorException("inner")
Evaluated: ErrorException("rethrow(exc) not allowed outside a catch block") == ErrorException("inner")
ERROR: There was an error during testing
```
I expect this to have a substantial positive impact on #13.
> Handle rethrow

- src/JuliaInterpreter.jl
- test/interpret.jl
Cherry picked from #19 since this is an independent change, discovered by the Debugger tests.
> fix getproperty

- src/JuliaInterpreter.jl
- src/interpret.jl
- src/localmethtable.jl
- test/juliatests.jl
Some of the infrastructure in Test takes a long time to run in interpreted mode; we can speed things up by running specific items in compiled mode.
> Support diversion of specific methods to Compiled

- .travis.yml
For now, Debugger.jl is a bit too tightly coupled to the internals of JuliaInterpreter.jl. Therefore, test that Debugger keeps working on CI.
> also test Debugger.jl on travis

- src/JuliaInterpreter.jl
- src/interpret.jl
- test/interpret.jl
- test/juliatests.jl
- test/toplevel.jl
- test/utils.jl
This collection of commits emerged from trying to address #13. With `julia --startup-file=no` (so no extraneous packages are loaded), we now get through `test/ambiguous.jl` and almost the first 1k lines of `strings/basic.jl`. I do not yet know if the failure to progress farther is a bug or just a performance problem.
> A grab-bag of correctness fixes

- .gitignore
- Manifest.toml
- Project.toml
- src/JuliaInterpreter.jl
- src/interpret.jl
- test/juliatests.jl
- test/utils.jl
This makes it much more feasible to run "all" of Julia's tests. The key advance is the ability to run a specified maximum number of statements in the interpreter, and abort early when that number is reached. Choosing a number of statements, rather than execution time, should make it easier to compare results on machines with different performance. On my laptop, the default settings run all of Julia's tests in < 5 minutes. This is *not* a sign that the interpreter is really efficient (it's not), just that it aborts a lot of slow tests.
Sample output is now visible in #13.
> Run Julia tests with resource limits, with worker process, and collate the results

- test/juliatests.jl
The `.*jl` argument made the test name not match against the STDLIB list.
> fix testing path for stdlibs

- src/JuliaInterpreter.jl
- src/generate_builtins.jl
- src/interpret.jl
- src/localmethtable.jl
- test/interpret.jl
- test/toplevel.jl
I discovered these while working on using this package to extract all method signatures from Base. Fixes #31 (though not enough to get the entire `tuple.jl` test running).
> More correctness fixes

- src/JuliaInterpreter.jl
- src/interpret.jl
Will likely break the Debugger tests.
> get rid of no-op "plain"

- src/JuliaInterpreter.jl
- test/toplevel.jl
Small fix to handle parsing Base signatures at statements like [this one](https://github.com/JuliaLang/julia/blob/f0d88dd12e9538a56f83695ba1662aa6357d721a/base/rounding.jl#L124-L135).
> Fix and test docstring extraction

- src/JuliaInterpreter.jl
- test/interpret.jl
This fix is of course a bit specious since all Core.Compiler methods are [fenced off](https://github.com/JuliaDebug/JuliaInterpreter.jl/blob/2f5a96f3ca851561bb06354cf2249ee45239ee0c/src/JuliaInterpreter.jl#L318-L320). I did that because something in the package was confusing Base and Core methods of the same name. Presumably that's fixable, but I haven't tackled it yet.
> Check output type of `prepare_call` more carefully. Fixes #51.

- docs/src/dev_reference.md
- docs/src/internals.md
- src/JuliaInterpreter.jl
- src/interpret.jl
- src/precompile.jl
- test/limits.jl
- test/toplevel.jl
- test/utils.jl
Fixes #56. (Better suggestions are welcome, of course.)
> Rename prepare_toplevel -> split_expressions

- src/interpret.jl
Fixes https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/63.
> handle `codeloc==0` in `linenumber`

- src/JuliaInterpreter.jl
- test/interpret.jl
- test/utils.jl
This circumvents #28 by "blacklisting" Base methods that have a `ccall` to `memcpy`. This won't catch packages, unfortunately, but this seems to be the best we can do.
> Avoid illegal instruction crash by circumventing ccall

- Project.toml
- src/JuliaInterpreter.jl
- src/interpret.jl
- test/interpret.jl
This addresses https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/13#issuecomment-464880123 by building a compiled call that gets dispatched to.
Unfortunately, generalizing this to handle :foreigncall does *not* fix #28. So we'll have to do that by a different means.
> Build compiled methods to handle llvmcall

- Project.toml
- src/JuliaInterpreter.jl
- test/juliatests.jl
I missed a couple of ccalls to memcpy in #68 (more issue #28).
> More like #28

- src/JuliaInterpreter.jl
Fixes https://github.com/JuliaDebug/Debugger.jl/issues/25.
There's something wonky about how we handle that function though:
```
julia> Debugger.@enter ∇(det)([1 2; 3 4])
In #13(args) at /home/pfitzseb/.julia/packages/Nabla/w019J/src/core.jl:188
188           args_ = Leaf.(Tape(), args)
189           y = f(args_...)
190           y isa Node || return zero.(args)
About to run: (Tape)()
1|debug> n
In #13(args) at /home/pfitzseb/.julia/packages/Nabla/w019J/src/core.jl:188
188           args_ = Leaf.(Tape(), args)
189           y = f(args_...)
190           y isa Node || return zero.(args)
191           ∇f = ∇(y)
About to run: (getfield)(<suppressed 78 bytes of output>, :f)
1|debug> n
In det(610) at none:0
1   1 ─ %1 = (tuple)(610)
2   │   %2 = (getfield)(610, :tape)
3   │   %3 = …
```
> more `unwrap_unionall`s for kw func handling

- src/JuliaInterpreter.jl
- src/breakpoints.jl
- src/interpret.jl
- test/breakpoints.jl
- test/runtests.jl
- test/toplevel.jl
Would be great to see what people think of the API. Currently the main API is:
- `breakpoint(f, sig, condition)`: add a breakpoint on entry to the method given by `which(f, sig)`
- `breakpoint(f, condition)`: add break-on-entry for all methods of `f`
Notably missing is `breakpoint(file, lineno, condition)`; I'll add that once I work on CodeTracking.jl integration. There are also `Breakpoints.enable`, `Breakpoints.disable`, and `Breakpoints.remove`, which can either take a specific `bp` to operate on or can be used as `Breakpoints.remove()` to get rid of all breakpoints.
There is also the non-exported all-powerful `breakpoint!(framecode, pc, condition)` that allows you set them wherever you want; this could easily be used when stepping through code to set a breakpoint at the current `pc`. …
> Add support for breakpoints (!)

- src/JuliaInterpreter.jl
- src/interpret.jl
In https://github.com/JuliaDebug/Debugger.jl/pull/31 (in preparation for breakpoint support) I changed the way the stack grows to correspond to JuliaInterpret (`push!` instead of `pushfirst!`). Debugging this took a bit longer than needed because there are functions in JuliaInterpreter only being used in Debugger.jl that assumes that the stack grew the other way. I moved over a few of them to Debugger.jl.
> fixes for stack inversion in Debugger.jl, also remove some unused functions

- Manifest.toml
- Project.toml
- docs/Manifest.toml
- docs/Project.toml
- docs/src/dev_reference.md
- src/JuliaInterpreter.jl
- src/breakpoints.jl
- src/interpret.jl
- test/breakpoints.jl
- test/interpret.jl
If the user is running an appropriate version of Revise, reported location will update as code moves around due to edits. Because methods can move files as well as from line-to-line, `linenumber` should not be used except internally. (Use `whereis` instead.)
If the user is not running Revise, CodeTracking should be harmless. Of course this makes this package sensitive to bugs in CodeTracking, but because it's a small package hopefully there won't be many of those before it becomes an asset.
Here's a fun demo (requires https://github.com/timholy/CodeTracking.jl/pull/10 to work with methods defined at the REPL):
```julia
julia> using JuliaInterpreter
julia> function mysum(A)
s = zero(eltype(A))
for a in A
s += a
end
return s
end
mysum (generic function with 1 method)
julia> …
```
> Integrate with CodeTracking and support line numbers when setting breakpoints

- docs/src/dev_reference.md
- src/JuliaInterpreter.jl
- test/interpret.jl
This provides a way to extract the local variables from a frame. The output is in a structured format to make it easier for different frontends to present it in their chosen way (ref https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/34#issuecomment-464000838).
Happy with inputs regarding the API chosen. Is a Vector the correct thing to return, perhaps a `Set` is more correct?
Creating a new struct `LocalVariable` has a bit of cognitive overhad over e.g. a tuple but might make it easier to change the behavior in the future.
> add a function to extract local variables from a frame

- src/JuliaInterpreter.jl
- test/interpret.jl
- test/utils.jl
The `evaluate_foreigncall!` that would otherwise be triggered ends up complaining.
>  Run `objectid` in Compiled mode (fixes #92) 

- src/interpret.jl
- test/interpret.jl
Does this seem OK, @pfitzseb? Methods annotated with `@inline` and the like have `codeloc = 0` for `pc==1`, but there doesn't seem to be any particularly good reason to have this fail.
> Try harder to find the line number

- Manifest.toml
- src/JuliaInterpreter.jl
- test/interpret.jl
> optimize!: don't look up GlobalRefs on the lhs of an assignment

- src/JuliaInterpreter.jl
- test/interpret.jl
REPL also uses sigatomic, but I don't expect to be interpreting REPL anytime soon.
> Run all Base users of `sigatomic` in compiled mode. Fixes #106

- src/interpret.jl
- test/breakpoints.jl
This reverts commit 28af3b350bb2f6ab427e55e8cadbe539a5ef5a5e.
This behavior actually doesn't make sense since it will only not break for things that are caught in the same frame which is a really weird special case.
> Revert "only break if we are throwing an uncaught exception (#89)"

- src/breakpoints.jl
- test/breakpoints.jl
This implements the last remaining way of setting breakpoints. Note that it depends on `signatures_at`, which in turn depends on Revise. This is the only truly robust solution I know of: for example, keyword-arg methods will need the breakpoint set in a gensymmed body method that cannot be easily discovered (https://github.com/JuliaLang/julia/issues/30908). I guess the question is whether we want a fallback that sometimes works.
> Support `breakpoint(filename, lineno)`

- src/interpret.jl
- test/breakpoints.jl
Second attempt at this.
Look down in the stack to see if something would catch this, otherwise break.
The option of always breaking on error should be easily implemented on top of this.
> only break if error would propagate to user

- src/interpret.jl
- test/breakpoints.jl
- test/interpret.jl
Unless each `push!` is guaranteed to have a corresponding `pop!`, we might end up with frames in the stack even when the function exits (#110). Currently, if we throw in `exec!` the `pop!` will not be executed, so when the stack unwinds after an error, we are left with frames in the stack.
This should fix that.
> pop top frame from stack if we throw evaluating it

- src/JuliaInterpreter.jl
- test/interpret.jl
> only do the getfield optimization when it is safe

- docs/src/dev_reference.md
- src/JuliaInterpreter.jl
- src/breakpoints.jl
- src/commands.jl
- src/construct.jl
- src/generate_builtins.jl
- src/interpret.jl
- src/localmethtable.jl
- src/precompile.jl
- src/types.jl
- src/utils.jl
- test/debug.jl
- test/runtests.jl
- test/utils.jl
I haven't really played much with Debugger.jl. Porting over some of its functionality is proving to be a useful exercise, as several of these commits generalize JuliaInterpreter in useful ways or detect problems that might not have surfaced so readily otherwise.
This is a WIP; I should probably transition to other things now. If folks want to chip in, I stopped [here](https://github.com/JuliaDebug/Debugger.jl/blob/4d9c0fc99b09ffdcf8ae1b4df8e6612ca0924884/test/stepping.jl#L93). Otherwise I'll pick this up again tomorrow.
> Implement core debug API here instead of Debugger.jl

- src/interpret.jl
https://github.com/JuliaLang/julia/pull/31095
> fix on julia master

- src/construct.jl
- test/interpret.jl
> fix vararg unionall handling

- docs/src/dev_reference.md
- src/interpret.jl
- src/utils.jl
- test/interpret.jl
> Docstring and dangling API update issue

- test/utils.jl
Slightly embarrassing, but before asking for help on #13 I should have checked that `juliatests.jl` actually works :sweat_smile:
> Fix the julia test harness for the new API

- deps/build.jl
- src/JuliaInterpreter.jl
- src/generate_builtins.jl
The current build system has the problem that if someone adds JuliaInterpreter on two julia versions, the second add will not build JuliaInterpreter (since it is already downloaded and assumed built). This will then give an error when loading it that it misses the file.
Instead, just run this on precompilation time if we cant find the file.
The negative is that we need to load the code for generating the builtin file every time we load the package but from my measurements it is within noise.
> move builtin generation logic to precompilation time

- src/utils.jl
- test/interpret.jl
- test/toplevel.jl
```jl
julia> f() = nothing
f (generic function with 1 method)
julia> fr = enter_call(f)
Frame for f() in Main at REPL[3]:1
1 1  1 ─     return nothing
julia> file, line = JuliaInterpreter.whereis(fr)
(("REPL[3]", 1), 1) # oooops
```
> fix typo in whereis

- benchmark/.gitignore
- benchmark/README.md
- benchmark/benchmarks.jl
Using https://juliaci.github.io/PkgBenchmark.jl/stable/export_markdown.html:
| ID                          | time            | GC time  | memory          | allocations |
|-----------------------------|----------------:|---------:|----------------:|------------:|
| `["long function 5_000"]`   |   5.560 ms (5%) |          |   1.31 MiB (1%) |       53490 |
| `["recursive other 1_000"]` |   1.405 ms (5%) |          | 173.80 KiB (1%) |        5031 |
| `["recursive self 1_000"]`  |   6.340 ms (5%) |          | 814.39 KiB (1%) |       28017 |
| `["throw long 1_000"]`      |   3.575 ms (5%) |          | 175.44 KiB (1%) |        5075 |
| `["tight loop 10_000"]`     | 674.890 ms (5%) | 2.856 ms |  58.04 MiB (1%) |     1857126 |
> add some benchmarks

- src/JuliaInterpreter.jl
- test/interpret.jl
We should probably enable AV heh.
Fixes #141
> fix interpreting getting env vars on windows

- src/commands.jl
- test/debug.jl
My sense is that `"s"` should step through wrappers but `"si"` should not. This adds such functionality and tests it.
One thing worth pointing out is that there is a certain amount of "junk" that gets lowered into the *caller*: using the examples in the new tests,
```julia
julia> Base.uncompressed_ast(first(methods(callopkw2)))
CodeInfo(
1 ─ %1 = (Main.opkw)(0, -1)
└──      return %1
)
```
but
```julia
julia> Base.uncompressed_ast(first(methods(callopkw5)))
CodeInfo(
1 ─ %1 = (:c, :d)
│   %2 = (Core.apply_type)(Core.NamedTuple, %1)
│   %3 = (Core.tuple)(-2, -3)
│   %4 = (%2)(%3)
│   %5 = (Core.kwfunc)(Main.opkw)
│   %6 = (%5)(%4, Main.opkw, 0)
└──      return %6
)
```
Note that we're in the caller of a kwarg function, not the kwarg function itself. For "normal" stepping (i.e., …
> Ensure that "s" steps through wrappers

- .travis.yml
> stop testing Debugger from here

- Manifest.toml
- docs/Manifest.toml
- src/JuliaInterpreter.jl
- src/types.jl
- src/utils.jl
- test/interpret.jl
Commited on top of #145 
Previously we couldnt see the source for stdlib files:
```jl
julia> @enter norm([1,2])
In norm(itr, p) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\LinearAlgebra\src\generic.jl:448
1   1 ── %1  = (isempty)(itr)
2   └───       goto #4 if not %1
3   2 ── %3  = (eltype)(itr)
About to run: (isempty)([1, 2])
1|debug> 
```
Now we can:
```jl
julia> @enter norm([1,2])
In norm(itr, p) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\LinearAlgebra\src\generic.jl:448
448       isempty(itr) && return float(norm(zero(eltype(itr))))
449       if p == 2
450           return norm2(itr)
```
The method printing is still wrong though.
>  work around problem with finding stdlib files 

- test/debug.jl
Stepping with "sg" currently errors with
```
ERROR: MethodError: no method matching #s5#3(::Symbol, ::Symbol)
Closest candidates are:
#s5#3(::Any, ::Any, ::Any, ::Any) at boot.jl:557
Stacktrace:
[1] (::Core.GeneratedFunctionStub)(::Any, ::Vararg{Any,N} where N) at .\boot.jl:522
[2] get_source at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\construct.jl:51 [inlined]
[3] #prepare_framecode#11(::Bool, ::Function, ::Method, ::Any) at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\construct.jl:141
[4] (::getfield(JuliaInterpreter, Symbol("#kw##prepare_framecode")))(::NamedTuple{(:enter_generated,),Tuple{Bool}}, ::typeof(JuliaInterpreter.prepare_framecode), ::Method, ::Type) at .\none:0
[5] #prepare_call#12(::Bool, ::Function, ::Any, ::Array{Any,1}) at …
```
> more thorough testing of commands

- docs/src/dev_reference.md
- src/JuliaInterpreter.jl
- src/breakpoints.jl
- test/breakpoints.jl
- test/debug.jl
Some day we hope to have more possibilities for triggering automatic breakpoints (issue #102). For now, let's at least establish an extensible user-level API.
> An export-worthy API for break_on_error

- src/types.jl
This was unused and untested (and undocumented). Do we want it for something or can it just be removed?
> get rid of unused function

- src/commands.jl
- src/construct.jl
- test/toplevel.jl
While trying to get https://github.com/timholy/Revise.jl/pull/243 to pass on nightly, I discovered that recent Julia versions no longer allow one to coerce certain expressions into a `CodeInfo`. So we're going to have to allow for the possibility that `prepare_thunk` will not return a `Frame`.
> Abandon attempts to force frame construction for "trivial" toplevels

- src/generate_builtins.jl
- src/interpret.jl
- test/debug.jl
With this:
```jl
julia> @enter Dense(10,10)(randn(10,10))
In Dense(x) at C:\Users\Kristoffer\.julia\packages\Flux\WSB7k\src\layers\basic.jl
>81    W, b, σ = a.W, a.b, a.σ
82    σ.(W*x .+ b)
83  end
84  
85  function Base.show(io::IO, l::Dense)
About to run: (getproperty)(<suppressed 109 bytes of output>, :W)
```
TODO:
Fixes https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/177
> step through invokes

- src/commands.jl
- src/utils.jl
- test/debug.jl
I am tired of stepping through `NamedTuple`, `pairs`, `merge`, and `Core.kwfunc`. This feels better.
> Step through preparation for kwarg calls

- src/commands.jl
- test/debug.jl
Currently, the debug command `:n` interacts a bit badly with the kwprep functionality, for example:
```jl
julia> function f(x, y)
sin(2.0)
g(x; y = 3)
end
f (generic function with 1 method)
julia> g(x; y) = x + y
g (generic function with 1 method)
julia> frame = JuliaInterpreter.enter_call(f, 2, 3)
Frame for f(x, y) in Main at REPL[23]:2
1* 2  1 ─      (sin)(2.0)
2  3  │   %2 = (:y,)
3  3  │   %3 = (Core.apply_type)(NamedTuple, %2)
⋮
x = 2
y = 3
julia> frame, pc = JuliaInterpreter.debug_command(frame, :n)
(Frame for f(x, y) in Main at REPL[23]:2
1  2  1 ─      (sin)(2.0)
2  3  │   %2 = (:y,)
3* 3  │   %3 = (Core.apply_type)(NamedTuple, %2)
4  3  │   %4 = (tuple)(3)
5  3  │   %5 = (%3)(%4)
⋮
x = 2
y = 3, 3)
julia> JuliaInterpreter.maybe_step_through_kwprep!(frame) # does nothing
Frame for …
```
> RFC: step through kwprep in next_line

- src/commands.jl
- test/debug.jl
This happens when the call is module-scoped. Fixes https://github.com/JuliaDebug/Debugger.jl/issues/141
> Allow an intervening statement in kw prep

- src/types.jl
- src/utils.jl
- test/interpret.jl
When an error is encountered in interpreted code, naively printing the stacktrace will just spew out internals of the interpreter which is not so nice to show a user. Fortunately, it is fairly easy to recreate the data structures that Base uses to print a "native" stacktrace from the leaf `Frame`. For example, with this PR:
```jl
julia> f() = "αβ"[2]
f (generic function with 1 method)
julia> break_on(:error)
julia> frame, bp = @interpret f();
julia> Base.display_error(stdout, bp.err, leaf(frame))
ERROR: StringIndexError("αβ", 2)
Stacktrace:
[1] string_index_err(::String, ::Int64) at strings/string.jl:12
[2] getindex_continued(::String, ::Int64, ::UInt32) at strings/string.jl:218
[3] getindex(::String, ::Int64) at strings/string.jl:211
[4] f() at REPL[122]:1
```
Compare vs the native …
> make `show_backtrace` and `display_error` work for Frame

- test/interpret.jl
https://github.com/JuliaDebug/JuliaInterpreter.jl/commit/fc15ae8a861680a4c66916b1c22affa4e18aba23 added a test with a builtin that doesn't exist on 1.0.
> fix test from builtin check on 1.0

- src/interpret.jl
- test/debug.jl
This allows a frontend to inspect the call stack after error by keeping the links between frames in case we would throw to top level and thus do something like:
```jl
julia> f() = "αβ"[2]
f (generic function with 1 method)
julia> frame = JuliaInterpreter.enter_call(f);
julia> err = try debug_command(frame, :c)
catch err
err
end
StringIndexError("αβ", 2)
julia> Base.display_error(stdout, err, leaf(frame))
ERROR: StringIndexError("αβ", 2)
Stacktrace:
[1] string_index_err(::String, ::Int64) at strings/string.jl:12
[2] getindex_continued(::String, ::Int64, ::UInt32) at strings/string.jl:218
[3] getindex(::String, ::Int64) at strings/string.jl:211
[4] f() at REPL[2]:1
```
This seemed like the easiest implementation and it feels like it should be fine since we are just throwing anyway, so we …
> only unlink frames if exception will not be thrown to top level

- src/generate_builtins.jl
Timings on kc/compiled_calls branch:
Before:
```
julia> @time @interpret plot(rand(5))
8.959916 seconds (32.77 M allocations: 1.415 GiB, 3.33% gc time)
julia> @time @interpret plot(rand(5))
7.090033 seconds (24.37 M allocations: 1.010 GiB, 3.47% gc time)
julia> @time @interpret plot(rand(5))
3.643197 seconds (13.57 M allocations: 485.439 MiB, 2.84% gc time
julia> @time @interpret plot(rand(5))
3.923732 seconds (13.57 M allocations: 485.295 MiB, 2.67% gc time)
```
After:
```
julia> @time @interpret plot(rand(5))
5.578359 seconds (21.28 M allocations: 863.471 MiB, 3.34% gc time)
julia> @time @interpret plot(rand(5))
2.970612 seconds (13.54 M allocations: 481.273 MiB, 2.18% gc time)
julia> @time @interpret plot(rand(5))
3.482414 seconds (13.45 M allocations: 476.643 MiB, 1.89% gc time) …
```
> prevent expensive compilation of map / splatting

- src/construct.jl
- test/toplevel.jl
Since we create modules incrementally as we advance through `split_expressions!`, when we extract docstrings we need to avoid duplicating the module definition itself.
Fixes https://github.com/JunoLab/Juno.jl/issues/271
CC @BioTurboNick
> Modules with docstring: don't replicate the module expression

- src/JuliaInterpreter.jl
- src/optimize.jl
See https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/230#issuecomment-477906104
I have not been able to have this situation occur artificially, even by explicitly trying to set the RNG seed.
> use non rng seed dependent uuid to avoid collisions

- src/optimize.jl
- test/interpret.jl
Use a `Val` wrapper instead of `Type` since `Val` works for everything. This means we need to do the call extraction after the foreigncall wrapper generation since we introduce a `Val` call. Fixes #233
> fix ccall with e.g. integer static parameters

- Project.toml
- src/optimize.jl
- test/interpret.jl
This happens for https://github.com/JuliaLang/julia/blob/b0427fc1b44adf8069e23e5bbaba194148eda4e5/stdlib/Mmap/src/Mmap.jl#L67  which I noticed when testing some random things on Linux.
> fix for varargs in ccall

- src/construct.jl
- src/interpret.jl
- src/localmethtable.jl
- src/utils.jl
Before:
```julia
julia> @time (p = @interpret(plot(rand(5))); @interpret(display(p)))
14.597646 seconds (72.11 M allocations: 2.350 GiB, 3.33% gc time)
```
After:
```julia
julia> @time (p = @interpret(plot(rand(5))); @interpret(display(p)))
11.713349 seconds (69.40 M allocations: 2.286 GiB, 3.02% gc time)
```
This is running on top of https://github.com/JuliaLang/julia/pull/31537.
> Micro-optimizations that reduce dynamic dispatch

- docs/src/dev_reference.md
- src/JuliaInterpreter.jl
- src/construct.jl
Makes it easier to experiment with #242.
@vchuravy, should be able to just `delete!` this module now from `compiled_modules` and experiment in the debugger.
We can also push modules that are very time consuming and we dont care about (like `Pkg.TOML`). Care of course has to be taken since any method that ends up dispatching through a compiled module will be "cut off" from the interpreter.
> use a Set of compiled modules instead of hardcoding it

- src/interpret.jl
- test/interpret.jl
Fixes https://github.com/JuliaDebug/Debugger.jl/issues/139
Previously we were not returning the correct exception type:
```jl
julia> f(2)
ERROR: UndefVarError: s not defined
julia> @interpret f(2)
ERROR: slot _5 with name s not assigned
```
> fix exception type for undefined variables

- src/construct.jl
- test/runtests.jl
Before
```jl
julia> @time (p = @interpret(plot(rand(5))); @interpret(display(p)))
12.059313 seconds (63.78 M allocations: 2.143 GiB, 2.58% gc time)
julia> @time (p = @interpret(plot(rand(5))); @interpret(display(p)))
12.198480 seconds (65.08 M allocations: 2.175 GiB, 2.66% gc time)
```
After
```jl
julia> @time (p = @interpret(plot(rand(5))); @interpret(display(p)))
9.768135 seconds (65.32 M allocations: 2.052 GiB, 2.97% gc time)
julia> @time (p = @interpret(plot(rand(5))); @interpret(display(p)))
9.531303 seconds (64.33 M allocations: 2.011 GiB, 3.06% gc time)
```
> go back to using a Vector for recycled frames

- Project.toml
- get rid of O(n^2) behavior in stacklength when enabling `break_on(:error)` (#212)
- make `show_backtrace` and `display_error` work for Frame (#211) 
- check the number of arguments to builtins https://github.com/JuliaDebug/JuliaInterpreter.jl/commit/fc15ae8a861680a4c66916b1c22affa4e18aba23
- frames now keep their callees when the interpreter throws an error (#214)
- fix assertion when breakpoint triggers during wrapper step through (#225)
- also build compiled calls for ccall (#216), (#227), (#231), (#236), (#237), (#240)
- fix a problem for methods with docstrings (#229)
- some general performance improvements (#243), (#245)
> bump Project for new release

- src/JuliaInterpreter.jl
- src/construct.jl
- src/interpret.jl
- src/utils.jl
Trivial, but I suspect we may want to tag 0.4.1 fairly soon.
> Fix for change in CodeInfo.slotnames type on julia master

- src/breakpoints.jl
- src/interpret.jl
- src/types.jl
- test/breakpoints.jl
This is pretty useful when debugging the interpreter because it has quite a lot of try catches so when there is a bug in the interpreter, the catch messes up the stacktrace.
> add a way to break on throw

- src/generate_builtins.jl
- src/interpret.jl
- src/utils.jl
- test/interpret.jl
These are all low-level optimizations. The cumulative effect is to go from ~18us/iteration in the `summer` benchmark to ~16us/iteration. One of the commits, the `is_vararg_type`, actually leads to a 3% hit on that benchmark, but it fixes what seems to be an outright mistake. (Before 22a8b2c it was not possible to step into any function that received `Union{}` as an argument; the case that I observed was for `promote_result`.)
On the `summer` benchmark, it seems the only remaining case of dynamic dispatch arises from https://github.com/JuliaLang/julia/issues/31565.
While performance improvements are always nice, my real goal in doing this is to prepare the way for a trial of the effect of lowered-code inlining (ref. https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/204#issuecomment-478 …
> More optimizations and a fix for `is_vararg_type`

- Project.toml
- Fix for change in CodeInfo.slotnames type on julia master (#251)
- Add a way to break on throw (#253)
- Exclude Union{} from is_vararg_type (#254)
- Various performance improvements (#254)
(Release motivated by the initial test failure in https://github.com/timholy/Revise.jl/pull/265)
> JuliaInterpreter v0.4.1

- src/commands.jl
- test/debug.jl
I must say I don't really understand the complications of the current implementation. So I removed most of it. Happy to close this if there are good examples why the complications are useful.
> RFC: simplify next_line! implementation

- docs/src/dev_reference.md
- src/commands.jl
This is breaking since it is changing the argument type of the `predicate`.
The `maybe_next_until!` was added because it felt weird to have a `maybe` version of the less general `next_call!` but not one for `next_until!`.
> generalize next_until! to take a frame and add maybe_next_until!

- docs/src/dev_reference.md
- src/commands.jl
- test/debug.jl
This is like `next_line!` except it guarantees you to move to something "later" in the source code. For example:
```jl
julia> function f(x)
s = 0
for i in 1:length(x)
s = s + 1
end
print(s)
return s
end
f (generic function with 2 methods)
julia> frame = JuliaInterpreter.enter_call(f, rand(100))
Frame for f(x) in Main at REPL[23]:2
1* 2  1 ─       s = 0
2  3  │   %2  = (length)(x)
3  3  │   %3  = (Colon())(1, %2)
⋮
x = [0.770521, 0.714896, 0.271307, 0.498012, 0.623033, 0.17695, 0.594108, 0.0127458, 0.287482, 0.396186  …  0.632738, 0.0830569, 0.586225, 0.287229, 0.0564309, 0.489518, 0.660743, 0.0207911, 0.908642, 0.925855]
julia>  JuliaInterpreter.until!(frame); frame
Frame for f(x) in Main at REPL[3]:2
1  2  1 ─       s = 0
2* 3  │   %2  = (length)(x)
3  3  │   %3  = (Colon())(1, %2)
4  3 …
```
> add `until_line!` to step to next line lower down in source code

- src/commands.jl
- test/debug.jl
Noticed from a test failure in Debugger.jl
> fix next_until! not properly returning breakpoint refs

- Project.toml
I want to release a new Debugger version soonish and need the `until` feature in a release.
Release notes:
- fix for undefined GlobalRefs (#268)
- fix next_until! not properly returning breakpoint refs (#270) 
-  add until_line! to step to line lower down in source code (#266) 
- changed the `predicate` for `next_until!` to take a `Frame` instead of a statement. This is a breaking change. (#269)
> release 0.5.0

- src/JuliaInterpreter.jl
- src/commands.jl
- src/interpret.jl
- src/optimize.jl
- src/types.jl
- src/utils.jl
- test/interpret.jl
This opens most of `Core.Compiler` to the interpreter. The unfortunate exceptions are some of the most interesting functions, the various `typeinf_*` functions: so far I have been unable to avoid segfaults from anything that starts a `ccall(:jl_typeinf_begin, ...)` block. However, hopefully this is still a considerable improvement from where we are currently. (Thoughts, @vchuravy?)
There are three substantive changes:
- Avoid using `Core.SlotNumber` and `Core.SSAValue`. Instead, we define equivalent types here and replace the values that come by from `Base.uncompressed_ast` with the local equivalents. This allows us to distinguish an `SSAValue` generated as a value from `Core.Compiler` methods vs one that's being used by the interpreter. Disadvantage: I suspect frame printing is broken. …
> Interpret most of Core.Compiler

- docs/src/dev_reference.md
- docs/src/index.md
- src/JuliaInterpreter.jl
- src/breakpoints.jl
- src/construct.jl
- src/types.jl
- src/utils.jl
- test/breakpoints.jl
- test/interpret.jl
- test/runtests.jl
The current breakpoint system immediately "lowers" the high level breakpoints given by a user (a high level breakpoint is for example a breakpoint for a method, or for a file:line) into a set of "lower level breakpoints" (given by a statement index into a FrameCode). This has a major drawback:
- After breakpoint insertion we do not know why a breakpoint was set in a FrameCode. Was it because it was a file:line breakpoint or because it was set on a method or a function etc?
- This makes it hard for a UI to show the active breakpoints. If a user sets a breakpoint on `convert` you don't want to show 60 breakpoints. From a users p.o.v, they added one breakpoint. That breakpoint can apply to multiple places, but it is still one. A user likely want to toggle / remove all the places where this …
> RFC: refactor breakpoints

- Project.toml
Note that this is against the newly-created `release-0.5` branch. See #284 for a release that will be on `master`.
- Support self-referential struct definitions (#283)
- Fix nightly (#286)
> JuliaInterpreter 0.5.2

- Project.toml
- src/construct.jl
- src/utils.jl
- test/interpret.jl
Part of the problem is detecting the llvmcall (esp in #112), but a bigger issue is that we need to check [`isempty(sparams)`](https://github.com/JuliaDebug/JuliaInterpreter.jl/blob/04d1fb5ce969d7e41df6f7bb9dd52d96049df1bb/src/optimize.jl#L165) because our [mini-interpreter](https://github.com/JuliaDebug/JuliaInterpreter.jl/blob/04d1fb5ce969d7e41df6f7bb9dd52d96049df1bb/src/optimize.jl#L277-L291) runs at toplevel and can't access `Expr(:static_parameter, n)`. I'm sure this is fixable, but this PR is a workaround that skips interpreting such methods altogether. It's probably OK because I think most methods that contain `llvmcall` are low-level and unlikely to be of interest to the majority of people doing debugging.
fixes #112, fixes #288
> Compile parametric methods that contain llvmcall

- src/interpret.jl
This allows you to count the number of times each statement gets executed. I used this in https://discourse.julialang.org/t/evaluation-speed-during-debugging/24520/13. Seems like it might be worth keeping around.
> Add some commented-out code for profiling

- src/construct.jl
The `$` character in [this line](https://github.com/aviatesk/JuliaInterpreter.jl/blob/01646ad1f035a8efa7f5a67465972ed72b84cc6c/src/construct.jl#L492) is currently not escaped and is being disappeared from the documentation.
This is better to be fixed since `determine_method_for_expr(:(sin([1, 2])))` is not the correct way to use this function and even causes an error.
- Closes #302
> Fix documentation of `determine_method_for_expr`

- benchmark/benchmarks.jl
```jl
julia> results["ccall ptr"]
minimum time:     1.607 ms (0.00% GC)
julia> results["ccall library"]
minimum time:     117.871 μs (0.00% GC)
```
We really need to fix the ccall stuff for when one calls a pointer heh.
> add benchmarks for ccall

- src/commands.jl
- src/interpret.jl
- test/utils.jl
I was kinda confused when looking at the `getlhs` calls and thinking "isn't this just always an SSAValue` and sure it is. IMO, this function is a non-needed abstraction.
> inline the one method `getlhs`

- src/commands.jl
- src/construct.jl
- src/interpret.jl
We might want to use a linear stack of memory in the future. It is then important that we unwind correctly (i.e return to the saved "stack pointer" after exiting the function).
This PR factors out a pattern we commonly used when returning from a function to simplify adding future functionality when this happens. I called it `unwind` but perhaps something like `return_from` is better?
> refactor out returning from a frame

- src/optimize.jl
- test/interpret.jl
Using the benchmark
```jl
function ccall_ptr(ptr, x, y)
ccall(ptr, Int, (Int, Int), x, y)
end
const ptr = @cfunction(+, Int, (Int, Int))
```
Before
```jl
julia> @btime @interpret ccall_ptr(ptr, 1, 5)
1.617 ms (963 allocations: 57.36 KiB)
6
```
After
```jl
julia> @btime @interpret ccall_ptr(ptr, 1, 5)
29.463 μs (189 allocations: 10.30 KiB)
6
```
> also compile ccalls to dynamic pointers

- src/breakpoints.jl
- src/construct.jl
- src/interpret.jl
- src/types.jl
- src/utils.jl
- test/breakpoints.jl
Old benchmarks:
```
"recursive other 1_000" => Trial(7.510 ms)
"recursive self 1_000" => Trial(2.450 ms)
"long function 5_000" => Trial(33.257 ms)
"throw long 1_000" => Trial(14.002 ms)
"tight loop 10_000" => Trial(213.216 ms)
```
vs this branch:
```
"recursive other 1_000" => Trial(7.502 ms)
"recursive self 1_000" => Trial(1.996 ms)
"long function 5_000" => Trial(30.500 ms)
"throw long 1_000" => Trial(13.406 ms)
"tight loop 10_000" => Trial(174.004 ms)
```
Take with a grain of salt, there is a fair amount of variance. But the last one is consistently cut to about 80% of the original.
> Replace the slow slotname Dict with a counter ("age")-based mechanism

- .gitignore
- docs/make.jl
- docs/src/internals.md
- src/construct.jl
- src/types.jl
- test/runtests.jl
This avoids creating all the tiny `Frame` objects over and over.
Running the tight loop benchmark:
```jl
julia> @btime @interpret f(X)
215.089 ms (1979122 allocations: 64.04 MiB)
julia> @btime @interpret f(X)
207.504 ms (1749055 allocations: 49.24 MiB)
```
The time difference is not that big but the allocations are only 75% and it is possible this will start to matter more when other things are more optimized.
> Create a "junk yard" even for Frames

- src/JuliaInterpreter.jl
- src/construct.jl
- src/localmethtable.jl
- src/optimize.jl
- src/types.jl
No performance difference but I feel this should be easier to maintain.
Slightly lifted from #309
> use our own struct for the local method table instead of TypeMapEntry

- src/construct.jl
- src/interpret.jl
- test/toplevel.jl
Encountered some problems while working on https://github.com/timholy/Revise.jl/issues/301
> Avoid errors on toplevel expressions that don't return frames

- src/construct.jl
- src/utils.jl
- test/interpret.jl
This is a temporary workaround for #330
> Don't interpret methods calling iolock_begin

- bin/generate_builtins.jl
- src/builtins.jl
- src/commands.jl
- test/interpret.jl
Fixes #344 
~~We still have some test failures on master:~~
```
Keyword arguments: Error During Test at /home/kc/JuliaPkgs/JuliaInterpreter.jl/test/debug.jl:179
Test threw exception
Expression: get_return(frame) == 6
expected return statement, got (SSAValue(15))(SSAValue(16), JuliaInterpreter.SlotNumber(3), JuliaInterpreter.SlotNumber(4))
Stacktrace:
[1] error(::String, ::Expr) at ./error.jl:42
[2] get_return(::Frame) at /home/kc/JuliaPkgs/JuliaInterpreter.jl/src/interpret.jl:609
[3] top-level scope at /home/kc/JuliaPkgs/JuliaInterpreter.jl/test/debug.jl:179
[4] top-level scope at /home/kc/julia/usr/share/julia/stdlib/v1.4/Test/src/Test.jl:1108
[5] top-level scope at /home/kc/JuliaPkgs/JuliaInterpreter.jl/test/debug.jl:163
Stepping over kwfunc preparation: Test Failed at …
```
> fixup for name change of #kw##invoke on 1.4

- Project.toml
- src/optimize.jl
- src/utils.jl
- test/interpret.jl
This doesn't work to fix #285 but it's close. The remaining problem is `JuliaInterpreter.CompiledCalls` doesn't know about other modules. Thoughts?
Relevant portion of debugging output from running the test in #285:
```julia
RetType = Ptr{SuiteSparse.CHOLMOD.C_Sparse{Tv<:Union{Complex{Float64}, Float64}}}
t.name = SuiteSparse.CHOLMOD.C_Sparse
t.name = Ptr
parametric_type_to_expr(RetType) = :(Core.Ptr{(SuiteSparse.CHOLMOD).C_Sparse{Tv}})
t.name = SuiteSparse.CHOLMOD.C_Sparse
t.name = Ptr
wrapargs = Any[:arg1, :arg2, :arg3, :arg4, :arg5, :arg6, :arg7, :arg8, :(::(Val){Tv})]
RetType = :(Core.Ptr{(SuiteSparse.CHOLMOD).C_Sparse{Tv}})
evalmod = JuliaInterpreter.CompiledCalls
def = :(function ccall_cholmod_l_allocate_sparse_libcholmod_1d562f76_7e37_11e9_2fa8_d190d118f371(arg1, arg2, arg3, arg4, …
```
> Make parametric_type_to_expr recursive (fixes #285)

- src/builtins.jl
- test/interpret.jl
- test/limits.jl
There is still an error in master in `limits.jl`:
```
Abort: Test Failed at /home/kc/JuliaPkgs/JuliaInterpreter.jl/test/limits.jl:39
Expression: (Aborted(frame, 1)).at.file == Symbol("util.jl")
Evaluated: var"fake.jl" == var"util.jl"
```
@timholy, do you have any idea about that one?
> fix breakage on master due to _apply_iterate

- src/interpret.jl
- test/interpret.jl
Prior to this the tests failed due to the following:
```julia
julia> using JuliaInterpreter
julia> sin(1)
0.8414709848078965
julia> @interpret sin(1)
0.8370984093755471
```
This turns out to be due to the new [`evalpoly`](https://github.com/JuliaLang/julia/blob/f39cdc0c7da8230b102051681c9378ce15d90235/base/math.jl#L106-L117), it was looking up the wrong framecode. This might have been a bug on all previous versions, but only detected now because of the change from macro to generated function.
> Look up correct framecode for invoke

- src/construct.jl
- src/utils.jl
- test/toplevel.jl
Formerly we were not recording such SSAValues as being used by later 
statements. Responsible for https://discourse.julialang.org/t/subtyping-with-union-as-type-parameter/32326
Incidentally, this also ensures that ssavalues are undefined upon frame start. Initially, the error message was rather strange. With some debugging statements, formerly we had
```julia
frame.framecode.used = BitSet([])
frame.framedata.ssavalues = Any[Main.Toplevel.NonFrame, svec("An expr that produces an `export nffoo` that doesn't produce a Frame\n"), :module => Main.Toplevel.NonFrame, Dict{Symbol,Any}(:typesig => Union{},:module => Main.Toplevel.NonFrame,:linenumber => 1,:binding => Main.Toplevel.NonFrame,:path => "none"), Base.Docs.DocStr(svec("An expr that produces an `export nffoo` that doesn't produce a …
```
> Store SSAValues used by :abstract_type and :primitive_type

- docs/src/dev_reference.md
- docs/src/index.md
- src/JuliaInterpreter.jl
- src/breakpoints.jl
- test/breakpoints.jl
Closes #261
I think the hooks fire too often.
For when creating breakpoints,
so there are two broken tests.
I only made 1 hook for all changes because I started to argue with myself as to if removal should trigger both the removal hook and the disable hook,
and concluded that i could just have one hook for everything than worry about those details,
that can be determined from the `BreakpointRef` anyway.
> Add hooks to breakpoint changes

- src/interpret.jl
- src/optimize.jl
- src/utils.jl
- test/toplevel.jl
Our optimization to pull out any internal calls causes problems when a structure hasn't yet been defined.
Fixes https://github.com/timholy/Revise.jl/issues/417
> Support recursive structure definitions

- src/construct.jl
This throws a more informative error when calling `split_expressions!` on e.g.
```
struct Foo end
module Foo end
```
> check if newmod is module in split_expressions!

- src/interpret.jl
- test/toplevel.jl
PR #363 broke certain types of structure definition. Hopefully this fixes it!
Fixes https://github.com/timholy/Revise.jl/issues/420
> Handle deeper call nesting in `struct`

- src/optimize.jl
- src/utils.jl
Fixes https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/383. Couldn't immediately come up with a test case that resulted in the invalid reinterpret.
Ultimately this is only a workaround, Base has a `static_eval` that returns NULL if the arguments aren't static (as with #383): https://github.com/JuliaLang/julia/blob/4e609128ff5c23424b175be300360ab07e90cba9/src/ccall.cpp#L541
> Only eval tuple specification to ccall, use dynamic semantics otherwise.

- .travis.yml
- Project.toml
- docs/Manifest.toml
- docs/make.jl
- docs/src/index.md
- src/commands.jl
- src/construct.jl
- src/interpret.jl
- test/breakpoints.jl
- test/interpret.jl
There are a couple of changes to lowering that recently crept in. There may be more coming, since Revise's signature tests are completely busted and I haven't yet figured out which package needs to be fixed.
> Fix on Julia nightly

- src/types.jl
- src/utils.jl
- test/eval_code.jl
Fixes https://github.com/JuliaDebug/Debugger.jl/issues/250
```jl
julia> function debugfun(non_accessible_variable)
garbage = ones(10)
map(1:10) do i
a = 5
@bp
garbage[i] + non_accessible_variable[i]
non_accessible_variable = 3
end
end
debugfun (generic function with 1 method)
julia> @run debugfun(randn(10))
Hit breakpoint:
In #3(i) at REPL[2]:4
2      garbage = ones(10)
3      map(1:10) do i
4          a = 5
●5          @bp
>6          garbage[i] + non_accessible_variable[i]
7          non_accessible_variable = 3
8      end
9  end
About to run: <(getfield)(var"#3#4"{Array{Float64,1}}(Core.Box([0.9940955858203274, -1.0692459508673031, 0.378124117...>
1|julia> garbage[1]
1.0
1|julia> non_accessible_variable[2]
-1.0692459508673031
1|julia> non_accessible_variable = 3
3
1|julia> …
```
> add closed over variables to locals and fix code evaluation on them

- src/commands.jl
- src/construct.jl
- src/types.jl
- src/utils.jl
I am using `linetable` in Revise, and I realized it would make more sense to centralize all the particulars here.
While I was at it, I decided to see what happens if I load packages that rank highest on non-ambiguity invalidations, namely DifferentialEquations, Makie, and DataFrames. The 2nd commit here gets rid of most of the non-ambiguous ones I found.
> Rework the linetable internal API and prevent more invalidations

- src/utils.jl
- test/eval_code.jl
```
1|debug>
In sin(x) at special/trig.jl:30
3  │          Core.NewvarNode(:(n))
4  │          absx = (abs)(x)
5  │    %5  = absx
6  │    %6  = ($(Expr(:static_parameter, 1)))(π)
> 7  │    %7  = (/)(%6, 4)
8  │    %8  = (<)(%5, %7)
9  └───       goto #6 if not %8
10  2 ── %10 = absx
11  │    %11 = (eps)($(Expr(:static_parameter, 1)))
About to run: (/)(3.141592653589793, 4)
1|julia> var"%5", var"%6"
(2.0, 3.141592653589793)
```
> add ability to evaluate ssavalues and locals

- src/construct.jl
- test/toplevel.jl
While I'm not aware of any problems caused by the former setting, when frames are being created for the purpose of analysis rather than execution it seems worth being able to control the evaluation.
Once this merges, OK to release a new version? #395 is a nice new feature, as long as you're comfortable with it I think we should get it out there.
> Allow caller to specify whether to eval an unlowerable thunk

- src/construct.jl
- test/debug.jl
The `local` mechanism only works inside `macro`
Fixes
```julia
julia> args = (1,)
(1,)
julia> kwargs = ()
()
julia> @interpret complicated_keyword_stuff(args...; kwargs...)
ERROR: UndefVarError: kwargs not defined
Stacktrace:
[1] top-level scope at /home/tim/.julia/dev/JuliaInterpreter/src/construct.jl:624
```
whereas the call works if you name `args` and `kwargs` something different.
> Use gensyms when extracting variables

- src/commands.jl
- src/utils.jl
- test/debug.jl
We were failing to detect kw functions that accepted vararg positional args.
> Detect splatting kwarg prep

- src/commands.jl
- src/utils.jl
To prevent invalidations one wants to avoid `==` and use `===` in circumstances where types can't be inferred.
I should have thought of this earlier, as it would have saved some uglification.
> Add an "egal" variant of `is_quotenode`

- src/utils.jl
Fixes https://github.com/JuliaDebug/Debugger.jl/issues/264
CC @mbauman.
> Widen allowed type of a CodeInfo.linetable

- src/utils.jl
- test/core.jl
If we try the new test in this PR on 1.4:
```julia
julia> function buildexpr()
items = [7, 3]
ex = quote
X = $items
for x in X
println(x)
end
end
return ex
end
buildexpr (generic function with 1 method)
julia> frame = JuliaInterpreter.enter_call(buildexpr)
Frame for buildexpr() in Main at REPL[2]:2
1 2  1 ─      items = (Base.vect)(7, 3)
2 3  │   %2 = (Core._expr)(:(=), :X, items)
3 3  │   %3 = $(Expr(:copyast, :($(QuoteNode(:(for x = X
⋮
julia> lines = JuliaInterpreter.framecode_lines(frame.framecode.src)
8-element Array{SubString{String},1}:
"1 ─     _J2 = (Base.vect)(7, 3)"
"│       (Core._expr)(:(=), :X, _J2)"
"│       \$(Expr(:copyast, :(\$(QuoteNode(:(for x = X"
"      #= REPL[2]:6 =#"
"      println(x)"
"  end))))))"
"│       _J3 = (Core._expr)(:block, :(#= REPL[2]:4 =#), %J2, :(#= …
```
> Improve robustness of `framecode_lines`

- src/construct.jl
- src/precompile.jl
- src/utils.jl
These make a substantial contribution to reducing latency for Revise 3, specifically in the area of handling atsign-require blocks.
> Improve inference and add precompiles in ExprSplitter

- src/optimize.jl
There are some invalidations triggered by `ColorTypes` definition of a `length` method for `Colorant` types. The annotation in the
comprehension is what fixes it. But there are a couple of other inference issues, and I may have been more specific in a previous annotation than merited by reality (not quite sure why it hasn't failed...).
> Fix some invalidations from `using Images`

- src/breakpoints.jl
- src/construct.jl
- src/interpret.jl
- src/utils.jl
This disabling of the debugging statements may be a bit unfortunate,
but we haven't needed them lately and they are easy to uncomment.
xref https://github.com/timholy/CodeTracking.jl/pull/73
> Improve inference in several places

- src/builtins.jl
- test/interpret.jl
`evaluate_call_recurse!` calls `maybe_evaluate_builtin`, and if
that doesn't return a `Some{Any}`, it uses the output as the
new `call_expr`. The next thing it does is look up the args.
Consequently, to avoid double-lookup, our expansion of `invoke` should
return the non-looked-up arguments.
Fixes #441
Closes #440
> Don't look up `invoke` args twice

- src/interpret.jl
- test/toplevel.jl
The symbol-lookup in `evaluate_methoddef` was not careful about
avoiding extending methods in Base when the method was unqualified.
Fixes https://github.com/timholy/Revise.jl/issues/579
-------------------
Unfortunately, this doesn't currently work:
```julia
julia> using JuliaInterpreter, Test
julia> module Namespace end
Main.Namespace
julia> @testset "Namespace" begin
frame = Frame(Namespace, :(sin(::Int) = 10))
while true
JuliaInterpreter.through_methoddef_or_done!(frame) === nothing && break
end
@test Namespace.sin(0) == 10
@test Base.sin(0) == 0
end
f = :sin
typeof(f) = Symbol
moduleof(frame) = Main.Namespace
Namespace: Error During Test at REPL[3]:1
Got exception outside of a @test
error in method definition: function Base.sin must be explicitly imported to be extended
Stacktrace: …
```
> Respect namespace in method definitions

- .github/workflows/CI.yml
Right now PRs from non-fork branches run twice on each platform.
This eliminates the redundancy.
~Also test 1.6 explicitly.~ Nvm, no binary yet.
Also push coverage.
> CI: less redundancy, push coverage

- .github/workflows/CI.yml
- Project.toml
- src/builtins.jl
- src/optimize.jl
- test/interpret.jl
This supports SSAValue args for cglobal while also fixing a bug
in which a GotoIfNot ended up going to the wrong statement.
The latter was a consequence of incorrect :call unnesting.
Fixes #455
Fixes #454
Fixes #415
Fixes https://github.com/JuliaDebug/Debugger.jl/issues/275
Improves #354
> Better handling of CGlobal & :call unnesting

- src/packagedef.jl
- test/interpret.jl
This has an llvmcall doing an atomic operation...just avoid the hassle
and call it directly.
Fixes #354
> Don't interpret `Base.load_state_acquire`

- src/breakpoints.jl
- src/interpret.jl
- src/utils.jl
eliminates some inferrability issues, and also removes some real errors around `GlobalRef`
> minor code quality improvements

- src/optimize.jl
- test/interpret.jl
This fixes the issue reported [here](https://github.com/julia-vscode/julia-vscode/issues/1693#issuecomment-781377955):
```
shell> cat test.csv
StartDate,Q2_Id
Start Date,"Please upload your savefile if you can - it'll be named something like __InterceptionXX.gz. You'll find it at:
Documents\My Games\Wesnoth\saves\ on Windows,or
~/.local/share/wesnoth//saves/ on Linux - ID"
2020-08-23 04:52:09,
2020-08-23 05:08:02,
2020-08-23 10:06:36,F_3smplS6AiQMH7Gy
julia> using CSV
julia> @interpret CSV.File("test.csv")
ERROR: TypeError: in typeassert, expected DataType, got Type{Array{T,N} where N}
Stacktrace:
[1] parametric_type_to_expr(::Type) at /home/pfitzseb/.julia/packages/JuliaInterpreter/hFiJ2/src/optimize.jl:251
[2] build_compiled_call!(::Expr, ::Symbol, ::Core.CodeInfo, ::Int64, ::Int64, …
```
> Try harder to unwrap UnionAlls

- src/breakpoints.jl
- src/construct.jl
- src/interpret.jl
- src/localmethtable.jl
- src/optimize.jl
I self-profiled JET and found some places where we can yet more improve:
```
julia> using JET
julia> tt = (JET.Frame, Bool)
(JuliaInterpreter.Frame, Bool)
julia> @time report_call(JET.step_expr!, tt)
```
<details><summary>On master</summary>
```julia
═════ 28 possible errors found ═════
┌ @ /Users/aviatesk/julia/packages/JuliaInterpreter/src/interpret.jl:590 JuliaInterpreter.step_expr!(JuliaInterpreter.finish_and_return!, frame, istoplevel)
│┌ @ /Users/aviatesk/julia/packages/JuliaInterpreter/src/interpret.jl:60 JuliaInterpreter.lookup_expr(frame, ##node#261)
││┌ @ /Users/aviatesk/julia/packages/JuliaInterpreter/src/interpret.jl:20 JuliaInterpreter.sparam_syms(Base.getproperty(Base.getproperty(frame, :framecode), :scope))
│││ for one of the union split cases, no matching method found for …
```
> eliminate type instabilities

- docs/src/dev_reference.md
- src/construct.jl
- test/debug.jl
This adds `JuliaInterpreter.interpreted_methods` as an easy way to compile all methods in a module except for a few of them (this takes precedence over both `compiled_methods` and `compiled_modules`)
Makes the implementation of [this proposal](https://discourse.julialang.org/t/debugging-in-juno-extremely-slow/53801/10?u=pfitzseb) much easier.
> Interpreted methods

- Project.toml
- src/utils.jl
- test/eval_code.jl
This fixes a pretty nasty segfault in Debugger.jl for me (see https://gist.github.com/simeonschaub/33313623fd14ecbaa147b6e77946154c). @KristofferC Was there a particular reason for introducing `maybe_quote` here and not just quote everything in a QuoteNode?
> always use QuoteNode in eval_code

- src/utils.jl
- test/interpret.jl
Fixes https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/472.
This seems strictly more useful than the current behavior, but maybe I'm missing something.
> Always interpret in current world

- src/optimize.jl
- test/interpret.jl
This was quite annoying to track down. The issue here was that
`replace_ssa!` modifies the passed expression, but it is possible for
there to be multiple references to the same copy of an expression in
`stmts`, so the replacement would be accidentally applied twice
generating wrong code.
> fix #479: buggy handling of ccall

- Project.toml
- docs/src/dev_reference.md
- src/construct.jl
- src/types.jl
Previously `FrameData.last_exception` is initialized with `nothing`,
which can't be distinguished from thrown objects, which technically can
be `nothing` as well.
This PR setups `_INACTIVE_EXCEPTION` singleton type and make
`FrameData.last_exception` initialized with it.
> setup `_INACTIVE_EXCEPTION`, which can be distinguished from thrown objects

- src/breakpoints.jl
- test/breakpoints.jl
Turns out that we can sometimes end up with duplicate slotnames, which breaks the current logic in `prepare_slotfunction`.
E.g. 
```
function debug(x)
for iter in Iterators.CartesianIndices(x)
i = iter[1]
c = i
a, b, c, d = tmp()
end
return x
end
```
results in 
```
julia> c = @code_lowered debug((1,2,3));
julia> c.slotnames
10-element Vector{Symbol}:
Symbol("#self#")
:x
Symbol("")
Symbol("")
:iter
:d
:b
:a
:c
:i
```
which means that we never insert the proper assignment for `i` (because `Symbol("")` is in there twice).
> Improve handling of duplicate slotnames

- src/optimize.jl
- test/interpret.jl
Now `DataType`s don't have `hasfreetypevars` field.
We can use `Base.has_free_typevars` instead while keeping backward compat.
> update to https://github.com/JuliaLang/julia/pull/41018

- src/optimize.jl
- src/packagedef.jl
These methods trigger compilation of `build_compiled_call!` during
Revise.revise(). Since they are essentially `ccall`-wrappers already,
there's not a lot of value in interpreting them.
Saves another ~100ms off the latency.
Closes #462
> Push a few ccalling methods onto compiled_methods

- Project.toml
- bin/generate_builtins.jl
- src/builtins.jl
- test/dummy_file.jl
- test/interpret.jl
Fixes https://github.com/timholy/Revise.jl/issues/625
> Don't splat in call to `append_any`

- src/optimize.jl
- test/interpret.jl
This comes up when trying to interpret the output of `code_warntype` for
example. Is this reasonable to support?
> allow interpreting TypedSlots

- src/utils.jl
- test/limits.jl
- test/utils.jl
This makes it easier to identify the caller of a macro.
This fixes a test failure on nightly.
xref #498
> Improve file/line attribution for macros

- Project.toml
- test/code_coverage/code_coverage.jl
- test/code_coverage/coverage_example.jl.cov
- test/interpret.jl
- test/limits.jl
Depends on JuliaLang/julia#42810 to pass. I did also observe some other
test failures on nightly I couldn't really explain.
> fix coverage test on nightly

- docs/src/internals.md
- src/interpret.jl
- src/optimize.jl
- src/precompile.jl
- src/utils.jl
We can eliminate this code since `:struct_type`/`:abstract_type`/`:primitive_type`
expressions no longer exist in v1.6 and higher.
> remove more legacy code

- src/construct.jl
- test/toplevel.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/2571.
This seems to be correct, but I don't quite understand the original reasoning for including the `:global` case in `push_modex!`.
> Fix toplevel-global behaviour in ExprSplitter

- src/builtins.jl
There is a shortcut that says that any builtin/intrinsic has an empty method table but this is not true on nightly for `Core._apply_iterate`:
```
julia> typeof(Core._apply_iterate).name.mt
[1] _apply_iterate(...) in Core
```
This takes the number of failures on nightly from 9 to 1 and makes Debugger.jl pass again on nightly.
> fix builtin detection

- src/utils.jl
- test/eval_code.jl
Fixes https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/517
> do not generate code for unused SSA values, slots and local variables in `eval_code`

- src/builtins.jl
- test/breakpoints.jl
There are cases (arguably a bit artificial but still) where after we expand a builtin, the function that we are going to run is another builtin, for example:
```
About to run: <(Core._apply_iterate)(iterate, Core._apply_iterate, (iterate, ...)
```
Currently, we cannot step through this since the second `_apply_iterate` will call into C. Solve this by recursing into the expander in the case where the expanded function is another builtin.
> recurse in builtin expansion if we get a new builtin when expanding

- src/commands.jl
- test/debug.jl
This was requested in https://discourse.julialang.org/t/debugger-usage-step-over-evaluations-in-function-arguments-straight-into-the-function/77018/7.
> add a new debug command that let's you step into the last call on a line

- src/utils.jl
Now `jl_gf_invoke_lookup` accepts an optional overlayed method table,
but actual code execution (as done by JuliaInterpreter) doesn't need to
care about it at this moment.
> update with JuliaLang/julia#44448

- test/code_coverage/code_coverage.jl
I found generated coverage files corresponding to source files a bit noisy, e.g. in a source tree view in my local editor.
I think we can just clean them up after test?
> clean up coverage files generated by test

- Project.toml
- docs/src/dev_reference.md
- src/breakpoints.jl
- src/construct.jl
- src/types.jl
- src/utils.jl
- test/breakpoints.jl
- test/runtests.jl
The current breakpoint code assumed:
- That all lineinfo for a method has the same file as the definition of the method.
- That the lines in the lineinfo was sorted.
- That a given `(file, line)` would only exist once in a method.
None of these are true in the presence of macro expansion. This PR makes us be a bit more careful about not doing any of the incorrect assumptions above. Now, for example, if there is a function like
```jl
function f(x)
x += 1
@info "..."
x += 1
@info "..."
return x
end
```
and a breakpoint is added at `logging.jl:370` (where the `@info` macro is expanded) it will actually stop twice there. Also, if you happen to add a breakpoint to a method at line 370 and the method contains an `@info` statement, it will no longer stop in `logging.jl:370`.
Fixes …
> fix some cases of setting breakpoints in functions that contain macro expansions

- src/breakpoints.jl
- test/breakpoints.jl
Fixes https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/371
> also break on `Core.kwfunc(f)` when setting a breakpoint on  `f`.

- src/utils.jl
Still we want to wait for the release of [next beta version](https://github.com/JuliaLang/julia/pull/44324) and change the version compat accordingly.
> adapt to upstream changes of `Core.Compiler._findsup`

- src/commands.jl
- src/utils.jl
ChainRulesCore gets loaded by a lot of packages. Its fallback methods
```julia
==(a, b::AbstractThunk)
==(a::AbstractThunk, b)
```
invalidate a lot of things, including much of the Serialization stdlib. But at least we can protect JuliaInterpreter.
> Fix some ChainRulesCore invalidations

- src/interpret.jl
Caused [crash](https://github.com/JuliaLang/julia/issues/44954) because of the incorrect semantics
> eval = is not functionally equivalent to global assignment

- src/utils.jl
- test/toplevel.jl
Solution as discussed in issue #538.
Without this change the first added test fails and the `collect` from the second test throws the `BoundsError` from #538 by calling `iterate(::ExprSplitter)`.
> Fix `is_doc_expr` by constraining number of args

- bin/generate_builtins.jl
- src/builtins.jl
- test/interpret.jl
This was added in #442 and inadvertently removed in #532.
However, the test in #442 was not stringent enough; the test added here
comes from #535.
Fixes #535
Fixes https://github.com/timholy/Revise.jl/issues/695
> Re-impose "no double lookup" for invoke

- src/interpret.jl
- test/interpret.jl
The fix in #505 should have only applied to `:cfunction`, not
`:foreigncall`.
fixes #536
> fix evaluation of :foreigncall with sparams

- .github/workflows/check_builtins.yml
- Project.toml
- test/check_builtins.jl
Use DeepDiffs.jl for printing nice diffs and only print diff if
something actually changed. Also stop hardcoding 1.9 as check for the
build being a nightly version.
> improve builtins consistency check

- src/interpret.jl
- src/optimize.jl
- src/utils.jl
- test/breakpoints.jl
- test/debug.jl
- test/eval_code.jl
- test/interpret.jl
- test/limits.jl
- test/utils.jl
It would be better to use a consistent style in our code base.
This is also aligned with the convention we're using for Julia base.
> NFC: normalize `x == ::Symbol` to `x === ::Symbol`

- src/utils.jl
This fixes a source of invalidations for StaticArrays when loaded together with Revise.
Previously, the now-annotated call site was inferred as `AbstractVector`, and the call to `mapany` then went through a completely uinferred call to `map!` (e.g., since `length(AbstractVector)` infers to `Any`).
I don't know if this is the ideal fix, but it at least seems correct and fixes the invalidation.
> Fix invalidations from StaticArrays' `map!`

- Project.toml
- src/optimize.jl
- test/interpret.jl
Instead of reconstructing the surface syntax we can just pass along the arguments to a `Expr(:foreigncall, ...)`.
Fixes https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/552
> simplify foreigncall handling

- src/optimize.jl
- test/core.jl
- test/interpret.jl
- test/runtests.jl
There is a funny call here https://github.com/JuliaLang/julia/blob/6740224b94a28dab629767ccfb8fe55e415361bd/base/strings/string.jl#L90 which apparently does not pass the argument as root which the standard foreigncall to this function does.
Fixes #560
> also count the number of arguments to cache the compiled ccall

- src/commands.jl
- test/debug.jl
This adds a new command `:sr` ("**s**tep (to) **r**eturn") for stepping until the current function is about to return. I find myself wanting this quite often since I want to inspect the state at that point.
> Add :sr debug command for stepping until return statement

- bin/generate_builtins.jl
- src/builtins.jl
- test/check_builtins.jl
Fixes https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/549
Also updates builtins
@maleadt
> Make generate_builtins path customizable for testing. Update builtins

- src/utils.jl
- test/interpret.jl
this works around a bug that occurs when there is an undefined sparams
Fixes #562
> rejigger the code to compute the method instance in stacktraces

- src/interpret.jl
These get called in the absence of knowledge about the second input,
so protecting them with `invokelatest` avoids invalidation risk.
> Protect `error` calls from invalidation

- src/commands.jl
- src/construct.jl
- src/optimize.jl
- src/types.jl
- src/utils.jl
- test/breakpoints.jl
- test/eval_code.jl
With the introduction of Core.kwcall, we need to adjust our
pattern-matching for the statements that prepare to dispatch on
kw-handling functions.
There are still a few broken tests on 1.9+, but this fixes the majority.
> Fix kw pattern matching, other changes on 1.9+

- .github/workflows/Documenter.yml
- docs/src/index.md
- src/construct.jl
The main change seems to be the `@` notation.
I was motivated by decreasing annoying noise, cf https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/575#issuecomment-1672030152
> Update some failing doctests

- src/interpret.jl
Fixes #574
@vchuravy, is just ignoring it the correct thing to do? It's just a compiler annotation?
> Ignore `:aliasscope` and `:popaliasscope`

- src/breakpoints.jl
Simply update the first line of the docstring to specify that the hook function must accept two arguments as explained further down in the docstring
> align arguments number in breakpoints hook docstring

- README.md
The badges seem less visible to some people than text links (I may have been in that camp once myself?), so let's have both.
Closes #587
> Add a second link to the docs from the README

- src/commands.jl
- src/interpret.jl
- src/optimize.jl
- src/packagedef.jl
- src/utils.jl
- test/core.jl
- test/limits.jl
The version compat is >=1.6, so we can expect `ReturnNode` and `GotoIfNot` are defined in `Core` always.
This should be good to go as far as 1.6 CI passes.
> remove old compats

- bin/generate_builtins.jl
- src/builtins.jl
https://github.com/JuliaLang/julia/pull/51319 added and removed a lot of builtins. Adapt `generate_builtins` accordingly
> adapt to array changes in Julia base

- src/interpret.jl
- src/optimize.jl
I don't expect this commit to fix the CI on :fire:, but since these changes are straightforward, we should be able to go ahead and merge this as is.
> adjust to the `:enter` IR changes made in JuliaLang/julia#52300

- src/interpret.jl
- src/optimize.jl
- src/types.jl
- src/utils.jl
There is only one bug in the base linearization pass that needs to be handled explicitly, otherwise linearization is fully guaranteed for IR.
> Remove buggy linearization pass

- .gitattributes
- docs/Manifest.toml
- docs/make.jl
- docs/src/index.md
- docs/src/internals.md
- src/construct.jl
Doctest is very fragile.
Using `@repl`, we can update documentation automatically.
> update docs and convert `jldoctest` to `@repl` blocks

- src/optimize.jl
The `.inferred` field is being removed in [1], so delete the assertion.
[1] https://github.com/JuliaLang/julia/pull/53219
> Adjust to upcoming compiler change

- .gitignore
- test/runtests.jl
Without this, the tests would stop prematurely, which means if there's even one unresolved regression, we'd miss out on detecting any additional regressions.
> use child `@testset` to get nicer test summary

- src/construct.jl
- src/interpret.jl
- src/types.jl
- src/utils.jl
- test/utils.jl
This contains some of the updates needed to keep working with the optimized debuginfo format (https://github.com/JuliaLang/julia/pull/52415). This is a draft, since someone needs integrate this to maintain support for old versions, where the old code is mostly marked here with my initials (jwn) and my initials should be removed entirely and instead the implementation in those places fixed.
> changes to adapt to compressed line table format

- src/interpret.jl
- test/breakpoints.jl
- JuliaLang/julia#54678: Now we need to declare `global` first before assigning a value to a binding in another module.
- JuliaLang/julia#54428: `base/logging.jl` is now `base/logging/logging.jl`
> adjustments to v1.11

- src/construct.jl
- src/precompile.jl
This makes JuliaSyntax happier when parsing the code of JuliaInterpreter. Note this doesn't affect normal usage of the package.
Found when testing out https://github.com/ericphanson/ExplicitImports.jl, which relies on source code parsing via JuliaSyntax.
```julia
julia> JuliaSyntax.parseall(JuliaSyntax.SyntaxNode, read("src/precompile.jl", String); version=v"1.11")
ERROR: ParseError:
module var"#Internal"
public(x::String) = false
└────┘ ── using public as an identifier is deprecated
Stacktrace:
[1] _parse(rule::Symbol, need_eof::Bool, ::Type{…}, text::String, index::Int64; version::VersionNumber, ignore_trivia::Bool, filename::Nothing, first_line::Int64, ignore_errors::Bool, ignore_warnings::Bool, kws::@Kwargs{})
@ JuliaSyntax ~/.julia/packages/JuliaSyntax/eqCSU/src/parser_api.jl:93
[2] …
```
> JuliaSyntax says `public` as an identifier is deprecated

- src/interpret.jl
- src/optimize.jl
For now, I've made the minimal changes needed to use JuliaInterpreter (and Revise) with v1.12. CI is still broken, so additional changes are needed.
Additionally, while making these changes, I found that the implementation of `JuliaInterpreter.optimize!` is quite illegal. This is an issue that should be resolved eventually, so I've left comments in optimize.jl regarding the known problems.
- closes #630
> minimum adjustments to make JuliaInterpreter work with v1.12

- bin/generate_builtins.jl
- src/builtins.jl
- src/interpret.jl
- src/optimize.jl
Fixes most of the semantic issues on 1.12 - there's still some test failures related to source locations, but should be usable for day-to-day things at least.
> More 1.12 compat

- src/interpret.jl
- src/utils.jl
`whereis` is already allowed to return `nothing`. It's possible for codeloc to be != 0, but for Core.Compiler to still be unable to produce a location. In that case, also return `nothing`.
> Don't error if we don't have line information

- .github/workflows/check_builtins.yml
It is rather confusing that https://github.com/JuliaDebug/JuliaInterpreter.jl/actions/workflows/check_builtins.yml lists two "CI" workflows which do really different things.
> Rename check_builtins.yml job from "CI" to "check_builtins"

- src/utils.jl
- test/interpret.jl
With this change, at least the tests in `test/interpret.jl` are passing
on nightly
> try harder to find code locations in `whereis`

- src/interpret.jl
- src/types.jl
These were added in https://github.com/JuliaLang/julia/pull/56523. This simply adds tracking for the world age to the interpreter, but does not use it for anything. JuliaInterpreter's current model of world age does not match Base anyway. We should fix that eventually, but it's probably easier to do that once https://github.com/JuliaLang/julia/pull/56509 and binding partitions are merged.
> Handle `:latestworld` expr

- .github/workflows/CI.yml
- Project.toml
- bin/generate_builtins.jl
- src/breakpoints.jl
- src/builtins.jl
- src/commands.jl
- src/construct.jl
- src/interpret.jl
- src/optimize.jl
- src/packagedef.jl
- src/types.jl
- src/utils.jl
- test/breakpoints.jl
- test/core.jl
- test/debug.jl
- test/interpret.jl
- test/limits.jl
- test/runtests.jl
- test/utils.jl
Maintaining this package that closely depends on Julia internals across multiple Julia versions is very cumbersome. Now that the LTS has been updated to 1.10, let's drop compatibility with earlier versions and simplify the code.
> bump the minimum supported Julia version to 1.10 (LTS)

- src/interpret.jl
- src/optimize.jl
Post-partitioning the executing world age matters for bindings lookup. JuliaInterpreter currently does not model world age correctly. That's a bigger issue. However, for now, just look up bindings in the latest world age, which mostly restores the unpartitioned behavior.
> Lookup bindings in the latest world

- src/optimize.jl
- src/utils.jl
The existing logic could not distinguish between ccall(foo) and ccall(:foo) and was giving wrong errors as a result.
> Correct logic for ccall symbol lookup

- src/interpret.jl
This is needed for CxxWrap.jl to avoid `unknown call f introduced by ccall lowering getindex`, see #613.
Probably for code like this:
```julia
push!(call_exp.args, :(@inbounds ccall(__cxxwrap_pointers[$funcidx][1], $c_return_type, ($(c_arg_types...),), $(argsymbols...)))) # Direct pointer call
```
This does fix my reproducer from #613.
But I don't really know how a proper test for this would look like.
cc: @barche
> allow getindex in lookup_or_eval :call

- bin/generate_builtins.jl
- src/builtins.jl
Compensates for the accidental push of
aca346cf36874a591b284c23b4adc1b194271001
> Fix builtins

- bin/generate_builtins.jl
- src/builtins.jl
JuliaInterpreter had special handling for `Core._call_latest` to allow
stepping into callees invoked in the latest world. In Julia 1.12,
`Core._call_latest` is now an alias for `Core.invokelatest`, but because
`generate_builtins` requires exact name matching, we had written the
implementation for `invokelatest` without the special handling applied
to `_call_latest`.
This should enable the `test/debug.jl` test for `f_inv_latest` to pass
on Julia 1.12.
> Update builtins, allow stepping into invokelatest

- src/optimize.jl
- test/toplevel.jl
With these changes we can get much of the way through the toplevel tests. This is good, because Revise is critically dependent on toplevel handling. (Despite Revise tests passing on Julia 1.12, it often fails on complex code bases.)
There are remaining world-age issues in the Non-frames test (and maybe others). My sense is that probably the only realistic way to get everything working well is to provide full support for world age in JuliaInterpreter.
> Fix world age issues in test/toplevel

- test/interpret.jl
This fixes a test failure that manifests only on Windows.
> Delay file removal

- src/commands.jl
- src/construct.jl
- src/interpret.jl
- src/optimize.jl
- src/utils.jl
One can use `llvmcall` without scoping it as `Base.llvmcall`. Thus we need a reliable way to find it independently of the GlobalRef module.
This was very difficult to debug, and I only figured out what was actually happening on my third attempt, after having fixed most of the other bugs in the package. The failure to identify an `llvmcall` led to a kind of error that we weren't handling correctly and which ended up changing the `pc` in a parent frame when it should have been changed in a leaf-frame. Thus we were getting absolutely crazy execution orders. The second commit adds several asserts that would have made catching it a bit easier.
Please do not squash when merging, since there is a chance we'll regret some of the `@assert`s.
> Try harder to find llvmcalls

- Project.toml
- src/utils.jl
- test/breakpoints.jl
This is largely a rewrite of `statementnumbers` for the new linetable representation. There are also adjustments to the tests. This largely completes the effort started in #606.
This allows `test/breakpoints.jl` to pass, with two warnings about invalid binding access (world-age).
Fixes #636
> Breakpoint setting for inverted linetable

- Project.toml
While #676 remains a priority, it's a bigger job and may be a breaking change. We should get the latest fixes out, since the package is now quite functional.
> Version 0.9.43

- Project.toml
- src/interpret.jl
- src/packagedef.jl
- src/utils.jl
- test/interpret.jl
- test/toplevel.jl
Currently, method evaluation assumes a syntax of the form
```julia
Expr(:method, :foo, %sig, %body)
```
whereas methods defined in an external method table will have the form
```julia
Expr(:method, mt, %sig, %body)
```
where `mt` references a `Core.MethodTable`, with the function directly extracted from the signature. This form assumes that the function is already defined, so we may rely on having `typeof(foo)` defined and provided as first argument. This slight difference simplifies the evaluation logic as now implemented in `evaluate_overlayed_methoddef`.
We used to evaluate both in the same way, leading to errors such as raised in https://github.com/timholy/Revise.jl/issues/646. While further changes are required to properly revise methods defined in external method tables, this PR at …
> Support external method tables in method evaluation

- bin/generate_builtins.jl
- docs/src/dev_reference.md
- src/builtins.jl
- src/interpret.jl
- src/optimize.jl
- test/debug.jl
- test/utils.jl
The `@lookup frame node` macro effectively inlines code in the caller’s context to choose lookup subroutines based on the type of `node`, but there’s no performance benefit to doing this.
A regular function call should deliver equivalent performance, and using a function improves maintainability. Below are the benchmark results:
> master (49220f956c88715b265ca6feed448d9f21a66f95)
```
julia> run(SUITE["recursive self 1_000"])
BenchmarkTools.Trial: 1254 samples with 1 evaluation per sample.
Range (min … max):  3.634 ms …  13.210 ms  ┊ GC (min … max): 0.00% … 0.00%
Time  (median):     3.845 ms               ┊ GC (median):    0.00%
Time  (mean ± σ):   3.979 ms ± 514.632 μs  ┊ GC (mean ± σ):  2.15% ± 6.18%
▄▇▆█▆▂▁
▃▇███████▇▇▇▅▄▅▄▄▄▃▃▂▂▂▂▁▁▁▁▂▂▁▂▂▂▂▂▂▂▂▁▂▂▂▂▂▂▂▃▂▂▃▂▂▂▂▂▁▂▂ ▃
3.63 ms …
```
> deprecate `@lookup` macro in favor of `lookup` function

- docs/src/dev_reference.md
- src/interpret.jl
- test/utils.jl
The additional logic implemented for `RecursiveInterpreter` seems to be no longer necessary. I think we can simply call `finish!` instead, since there is no strong reason to add `caller->callee` relation to the nested `CodeInfo` frame within `:thunk` expression.
Confirmed LoweredCodeUtils/Revise/Debugger still pass their test suites with this change.
> remove the new `finish_nested_frame!` interface

- docs/src/dev_reference.md
- src/construct.jl
- src/interpret.jl
- src/localmethtable.jl
- src/types.jl
- src/utils.jl
- test/interpret.jl
Implemented, being inspired by JuliaDebug/JuliaInterpreter.jl#680, thinking it might be useful in the near future for JET's use case.
The overlay interpretertation is enabled by overloading `JuliaInterpreter.method_table(recurse)`, but maybe the entire `recurse`-overload mechanism itself needs to be aligned with the `AbstractInterpreter` design and properly organized.
Since this interface will also be needed for JET,
I'll probably work on it soon.
> implement a system for interpreting overlay methods

- bin/generate_builtins.jl
- src/builtins.jl
- test/toplevel.jl
Adjusts for JuliaLang/julia#57965.
> update builtins.jl and add some simple tests for `using/import` evaluation

- src/construct.jl
- use `getglobal`/`isdefinedglobal` instead of `getfield`/`isdefined` - removed unnecessary `LineNumberNode` attachment
> minor updates

- bin/generate_builtins.jl
- src/builtins.jl
It's not a huge perf difference (a couple of percent) but it cleans up `@profile`.
> avoid going into subtyping for checking if a function is a `Core.Builtin`

- test/interpret.jl
Nightly became more strict about equality among `QuoteNode`s (https://github.com/JuliaLang/julia/pull/58661). This expands the comparison to circumvent Base's new behavior.
> Change `==` test for `deepcopy(::QuoteNode)`

- src/optimize.jl
Relies on https://github.com/JuliaLang/julia/pull/59165 for exact
accuracy, otherwise we're relying on hoping that `eval` on a random
expression is safe and correct (both hopes are quite false).
> make dynamic-ccall detection more correct
